### ISSUE TITLE
Confused Unga Bunga

### ISSUE THREAD

**Issue by ChaO-0** [yudi7ll/docker-kalilinux#1]
![image](https://user-images.githubusercontent.com/37824174/164588705-f1843ccc-ad92-4c1f-97ad-4494fd3cb517.png)

**Comment by yudi7ll** [comment]
![136biz26i2c71](https://user-images.githubusercontent.com/35747911/196598655-58e34dd2-8438-43fc-b5db-80c34acbd7d4.jpg)

**Comment by FajarAlnito** [comment]
![photo_2022-10-19_13-00-19](https://user-images.githubusercontent.com/40420547/196601536-280990fd-8a72-4c16-9c75-0a1f23f11ef8.jpg)
